sudo: false
language: node_js
node_js:
- '8'
env:
    global:
        - secure: "2wAzWTw6dwhZFzPbBElQlHdgyCPKV8qAyPIZJF+lHrYKM8UeQ7AWWUzVEVg9SHiwpIme+TKpv38dRCQ2sSsZ6/H5okB7DZoLTGezUVzZvaKoIzs8Ebfcgd7vTtqFhfr6xvfNXodXZEnOXtr3lrVF1HqFJYiNnGHnVci94nTsyhdFtLNgoJtYN0WmLVAQ1p9zaJczATovTxOfd0CGBIbLoHtikW6crcFcK22/5urxQ38PlU6TEq+VRJoviushjDmP1CG4f96PY/IwuXtqKOwFjaQEbLwaGW5osMaY2+39+UrKHhDi4LSNaz6V2kQu3Jzs5C9QciBkxSpYzAUKHDU/yvQftrFmOrDNKSCKJOfe84JwK/c1c/j9zZiB9vD14xeO+9tmShrm/LwDhBerg8krJJevcA/92zKmZJN1iEV0Pwele/Cc22NESSzKhhb0ur0grYCAr5S8ZwdV5XJiOy0GJ5PsRPZ8rU35HB5uhj/dOK2aYjeovnEC+xqUQEoZ7KG7+7HqOPqxUvGqWkQqjl5J0DBojxuMxKGTrZKRpWGW7CW1WhUfEZ+eUNYZGjNfOwWUIJhs5X/qX/02NOLjdVJMMarUWPiWjfI2va2b0MRfKRiCNd31CTprwTgsTzQizFGVKHat5EZe3VPPEeAqiRvPBA8KExvVii7ZI8K7DSKsmXc="
        - secure: "jGtMAwVn5JP1Bd137Yx8YCsqeZJZfuaEfT00Y2+w/L3IDpea7wpDGEM+2XNaUy6+2jTvRDkFv4y79CxyyGbOEzlq6TwAKVkYc5Ez9RV5VXPpTaMDbahvBM+tWGFdvnbDoMMW9lQyK4VjTrE+z5D2ek/9JeIoFS/I4qvpE2aaMOxZWXkqQUKawAgH8JKUmsgiamsQsqSKhAX4YjUR6Qeg/DTbe+8E0lw8uNUms+CxhaQVaVZR4tZBRzhiUuN4e50H4bftvUmkfjY/R4zO0Yq1gsZ1pO7NGdC5KSpy+fn/U1NV2XLgQ+Wr8hR0CG1JeLC4uXxZ5+6mTpC27sx2ezc19YZL/cgPL7Xbxa+IZSYkiM0EkR/5tQ/IGYsRq+kL+9cbJB6AMgnHHBBg1UDhbhz+lCCFlcssjqYSj/bqjV+OCl7TKao9dTF99X94INpXETs25c/6HZ1PGeRUpF/EI0uZBFZb6ZkSG/FZosz/eKgbe1Zon4EhL5EqdSiOlPuJvrnHAnBbbqOwq3lUTTxu78WB5z4oJtVuKaY+nOxtyyKDkVXy75w+y2OJ5l1Ov5Bstfc4cv9PdwHD5FojzyokJ60nmsq0/ZLjN9dXRaluFMlmHp9Z/QYh4mcyND6bjeZ0vtSr9oQUu7atisI73496mEseLMDbXfx1OX+HPszkUHIrNoY="
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_install:
    - wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
    - unzip BrowserStackLocal-linux-x64.zip
    - ./BrowserStackLocal --key $BROWSER_STACK_ACCESS_KEY --local-identifier karma.$(date +%s) --force > /dev/null &
    - sleep 15
